=== Zafiro2004/DAM-Primer-Curso/Lenguaje de Marcas/Ejercicios/ExercicisXML4/cataleg.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="cataleg">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="cotxe" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="marca" type="xs:string">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:minLength value="2"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>

                            <xs:element name="model" type="xs:string">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:minLength value="1"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>

                            <xs:element name="any" type="xs:integer">
                                <xs:simpleType>
                                    <xs:restriction base="xs:integer">
                                        <xs:minInclusive value="1990"/>
                                        <xs:maxInclusive value="2025"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>

                            <xs:element name="preu" type="xs:decimal">
                                <xs:simpleType>
                                    <xs:restriction base="xs:integer">
                                        <xs:minExclusive value="0"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>

                            <xs:element name="extres" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="extra" type="xs:string" maxOccurs="unbounded">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:minLength value="2"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>

                        </xs:sequence>
                        <xs:attribute name="id" use="required"/>
                        <xs:attribute name="combustible" use="optional">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:enumeration value="gasolina"/>
                                    <xs:enumeration value="diesel"/>
                                    <xs:enumeration value="hibrid"/>
                                    <xs:enumeration value="electric"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                        <xs:attribute name="estat" default="disponible">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:enumeration value="disponible"/>
                                    <xs:enumeration value="reservat"/>
                                    <xs:enumeration value="venut"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                        <xs:attribute name="moneda" fixed="EUR"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Zafiro2004/DAM-Primer-Curso/Lenguaje de Marcas/Ejercicios/ExercicisXML4/cataleg.xml
<?xml version="1.0" encoding="UTF-8"?>
<cataleg
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="cataleg.xsd">
    <cotxe id="c1" combustible="gasolina" moneda="EUR">
        <marca>Seat</marca>
        <model>Ibiza</model>
        <any>2020</any>
        <preu>14500</preu>
        <extres>
            <extra>Bluetooth</extra>
            <extra>Càmera posterior</extra>
        </extres>
    </cotxe>
    <cotxe id="c2" combustible="electric" estat="reservat" moneda="EUR">
        <marca>Tesla</marca>
        <model>Model 3</model>
        <any>2023</any>
        <preu>38900</preu>
        <extres>
            <extra>Autopilot</extra>
        </extres>
    </cotxe>
    <cotxe id="c3" combustible="diesel" moneda="EUR">
        <marca>Volkswagen</marca>
        <model>Golf</model>
        <any>2019</any>
        <preu>17900</preu>
    </cotxe>
    <cotxe id="c4" combustible="hibrid" moneda="EUR">
        <marca>Toyota</marca>
        <model>Corolla</model>
        <any>2022</any>
        <preu>23000</preu>
    </cotxe>
    <cotxe id="c6" combustible="diesel" moneda="EUR">
        <marca>Kia</marca>
        <model>Rio</model>
        <preu>6000</preu>
        <any>2018</any>
    </cotxe>


</cataleg>
